apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: linuxserver/plex
        env:
        - name: asdasd
          value: asdasdasdasdasd
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256mi
          limits:
            cpu: 1000m
            memory: 1gi
